Repository Team-ForPets/forpets-web, pull requests merged in 2025-03, with the labels that each got.

#1 FR-4 husky 설정
  .github/pull_request_template.md
  .gitmessage
  .husky/.gitmessage
  .husky/commit-msg
  .husky/pre-commit
  .husky/prepare-commit-msg
  package-lock.json
  package.json
Labels: chore

#2 FR-5 [BE] 백엔드 환경설정
  .idea/.gitignore
  .idea/forpets-web.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  be/.gitattributes
  be/.gitignore
  be/build.gradle
  be/docker-compose.yml
  be/gradle/wrapper/gradle-wrapper.jar
  be/gradle/wrapper/gradle-wrapper.properties
  be/gradlew
  be/gradlew.bat
  be/settings.gradle
  be/src/main/java/com/forpets/be/BeApplication.java
  be/src/main/java/com/forpets/be/domain/animal/controller/tmp
  be/src/main/java/com/forpets/be/domain/animal/dto/tmp
  be/src/main/java/com/forpets/be/domain/animal/entity/tmp
  be/src/main/java/com/forpets/be/domain/animal/repository/tmp
  be/src/main/java/com/forpets/be/domain/animal/service/tmp
  be/src/main/java/com/forpets/be/domain/chatroom/controller/tmp
  be/src/main/java/com/forpets/be/domain/chatroom/dto/tmp
  be/src/main/java/com/forpets/be/domain/chatroom/entity/tmp
  be/src/main/java/com/forpets/be/domain/chatroom/repository/tmp
  be/src/main/java/com/forpets/be/domain/chatroom/service/tmp
  be/src/main/java/com/forpets/be/domain/servicestatus/controller/tmp
  be/src/main/java/com/forpets/be/domain/servicestatus/dto/tmp
  be/src/main/java/com/forpets/be/domain/servicestatus/entity/tmp
  be/src/main/java/com/forpets/be/domain/servicestatus/repository/tmp
  be/src/main/java/com/forpets/be/domain/servicestatus/service/tmp
  be/src/main/java/com/forpets/be/domain/servicevolunteer/controller/tmp
  be/src/main/java/com/forpets/be/domain/servicevolunteer/dto/tmp
  be/src/main/java/com/forpets/be/domain/servicevolunteer/entity/tmp
  be/src/main/java/com/forpets/be/domain/servicevolunteer/repository/tmp
  be/src/main/java/com/forpets/be/domain/servicevolunteer/service/tmp
  be/src/main/java/com/forpets/be/domain/user/controller/tmp
  be/src/main/java/com/forpets/be/domain/user/dto/tmp
  be/src/main/java/com/forpets/be/domain/user/entity/tmp
  be/src/main/java/com/forpets/be/domain/user/repository/tmp
  be/src/main/java/com/forpets/be/domain/user/service/tmp
  be/src/main/java/com/forpets/be/global/config/tmp
  be/src/main/java/com/forpets/be/global/entity/BaseTimeEntity.java
  be/src/main/java/com/forpets/be/global/exeption/tmp
  be/src/main/java/com/forpets/be/global/response/ApiResponse.java
  be/src/main/resources/application.properties
  be/src/test/java/com/forpets/be/BeApplicationTests.java
Labels: chore

#3 FR-6 [BE] 회원가입 로직 추가
  be/.env.example
  be/src/main/java/com/forpets/be/domain/animal/dto/request/tmp
  be/src/main/java/com/forpets/be/domain/animal/dto/response/tmp
  be/src/main/java/com/forpets/be/domain/chatroom/dto/request/tmp
  be/src/main/java/com/forpets/be/domain/chatroom/dto/response/tmp
  be/src/main/java/com/forpets/be/domain/servicestatus/dto/request/tmp
  be/src/main/java/com/forpets/be/domain/servicestatus/dto/response/tmp
  be/src/main/java/com/forpets/be/domain/servicevolunteer/dto/request/tmp
  be/src/main/java/com/forpets/be/domain/servicevolunteer/dto/response/tmp
  be/src/main/java/com/forpets/be/domain/user/controller/UserController.java
  be/src/main/java/com/forpets/be/domain/user/dto/request/tmp
  be/src/main/java/com/forpets/be/domain/user/dto/response/tmp
  be/src/main/java/com/forpets/be/domain/user/entity/Role.java
  be/src/main/java/com/forpets/be/domain/user/entity/User.java
  be/src/main/java/com/forpets/be/domain/user/repository/UserRepository.java
  be/src/main/java/com/forpets/be/global/auth/controller/AuthController.java
  be/src/main/java/com/forpets/be/global/auth/dto/request/SignupRequestDto.java
  be/src/main/java/com/forpets/be/global/auth/dto/response/SignupResponseDto.java
  be/src/main/java/com/forpets/be/global/auth/service/AuthService.java
  be/src/main/java/com/forpets/be/global/config/SecurityConfig.java
Labels: feat

#5 FR-14 [BE] 응답 데이터에 생성일, 수정일 추가
  be/src/main/java/com/forpets/be/BeApplication.java
  be/src/main/java/com/forpets/be/global/auth/dto/response/SignupResponseDto.java
Labels: feat

#6 FR-11 [FE] react 로그인 페이지 구현
  fe/public/assets/kakao-login-button.png
  fe/public/assets/naver-login-button.png
  fe/src/components/Banner.jsx
  fe/src/components/Footer.jsx
  fe/src/components/Header.jsx
  fe/src/pages/Home.jsx
  fe/src/pages/Login.jsx
  fe/src/router/index.jsx
Labels: feat

#7 FR-19 [BE] 회원가입 시 username/nickname 검증 로직 추가
  be/src/main/java/com/forpets/be/domain/user/controller/UserController.java
  be/src/main/java/com/forpets/be/domain/user/dto/response/UserCheckResponseDto.java
  be/src/main/java/com/forpets/be/domain/user/dto/response/tmp
  be/src/main/java/com/forpets/be/domain/user/repository/UserRepository.java
  be/src/main/java/com/forpets/be/domain/user/service/UserService.java
  be/src/main/java/com/forpets/be/domain/user/service/tmp
Labels: feat

#9 FR-18[FE] 봉사자 등록하기 구현
  fe/package-lock.json
  fe/package.json
  fe/src/pages/RegisterVolunteer.jsx
Labels: feat

#11 FR-15 [FE] 마이페이지 기초 구현
  fe/src/components/Header.jsx
  fe/src/components/mypage/ProfileCard.jsx
  fe/src/pages/MyPage.jsx
  fe/src/router/index.jsx
Labels: feat, fix

#12 FR-20 [FE] 메인 페이지 구현
  fe/index.html
  fe/src/components/KakaoMap.jsx
  fe/src/components/MainAnimalCard.jsx
  fe/src/components/MainCard.jsx
  fe/src/components/MainVolunteerCard.jsx
  fe/src/pages/Home.jsx
Labels: feat

#10 FR-18 [FE] 봉사자 등록하기 구현
  fe/src/pages/RegisterVolunteer.jsx
Labels: fix

#13 FR-25 [BE] CORS 설정 추가
  be/src/main/java/com/forpets/be/global/config/SecurityConfig.java
Labels: feat

#14 FR-21 [FE] 로그인 api 연동
  fe/package-lock.json
  fe/package.json
  fe/src/api/authApi.js
  fe/src/api/axios.js
  fe/src/components/Header.jsx
  fe/src/components/KakaoMap.jsx
  fe/src/components/PrivateRoute.jsx
  fe/src/pages/Home.jsx
  fe/src/pages/Login.jsx
  fe/src/router/index.jsx
  fe/src/store/slices/authSlice.js
  fe/src/store/slices/bucketSlice.js
  fe/src/store/store.js
  fe/vite.config.js
Labels: chore, feat

#15 FR-13 [FE] 회원가입 페이지 구현
  fe/src/api/authApi.js
  fe/src/pages/Signup.jsx
Labels: feat

#17 FR-26 [FE] 회원가입 페이지 css 적용 및 이벤트 수정
  fe/src/api/authApi.js
  fe/src/pages/Signup.jsx
Labels: feat

#19 FR-23 [FE] 마이페이지 프로필 카드 컴포넌트 구현
  fe/src/api/mypageApi.js
  fe/src/components/mypage/ProfileCard.jsx
  fe/src/components/mypage/ProfileEditCard.jsx
  fe/src/pages/MyPage.jsx
  fe/src/router/index.jsx
Labels: feat

#20 FR-32 [BE] 마이페이지 프로필 조회 API 구현
  be/src/main/java/com/forpets/be/domain/user/my/controller/MyController.java
  be/src/main/java/com/forpets/be/domain/user/my/dto/response/MyProfileResponseDto.java
  be/src/main/java/com/forpets/be/domain/user/my/service/MyService.java
Labels: feat

#22 FR-30 [FE] 메인페이지 지도, 주소검색 구현
  fe/package-lock.json
  fe/package.json
  fe/src/components/DaumPost.jsx
  fe/src/components/KakaoMap.jsx
  fe/src/pages/Home.jsx
Labels: feat

#23 FR-33 배포 테스트
  .env.example
  .github/workflows/workflows.yml
  be/Dockerfile
  docker-compose.yml
  fe/Dockerfile
  fe/nginx.conf
  fe/package.json
  fe/src/router/index.jsx
  fe/templates/default.conf.template
  fe/templates/https.conf.template
Labels: feat

#25 FR-36 [BE] SecurityConfig에 cors 추가 적용
  be/src/main/java/com/forpets/be/global/config/SecurityConfig.java
  be/src/main/resources/application.properties
Labels: feat

#26 FR-39 [FE] axios 토큰 연결
  fe/src/api/axios.js
Labels: chore, feat

#27 FR-31 [BE] 로그아웃 기능 구현
  be/.env.example
  be/build.gradle
  be/docker-compose.yml
  be/src/main/java/com/forpets/be/global/auth/controller/AuthController.java
  be/src/main/java/com/forpets/be/global/auth/service/AuthService.java
  be/src/main/java/com/forpets/be/global/security/jwt/JwtAuthenticationFilter.java
  be/src/main/resources/application.properties
  fe/src/api/authApi.js
  fe/src/components/Header.jsx
Labels: chore, feat, fix

#28 FR-34 [FE] 마이페이지 프로필 조회 API 연동
  fe/.env.example
  fe/src/components/mypage/ProfileCard.jsx
  fe/src/pages/MyPage.jsx
Labels: feat

#29 FR-29 [BE] 회원가입 시 Gmail smtp를 사용한 이메일 인증 로직 구현
  be/build.gradle
  be/src/main/java/com/forpets/be/global/auth/controller/AuthController.java
  be/src/main/java/com/forpets/be/global/auth/service/AuthService.java
  be/src/main/java/com/forpets/be/global/mail/controller/MailController.java
  be/src/main/java/com/forpets/be/global/mail/dto/request/AuthenticationRequestDto.java
  be/src/main/java/com/forpets/be/global/mail/dto/response/AuthenticationCodeResponseDto.java
  be/src/main/java/com/forpets/be/global/mail/service/CodeGenerator.java
  be/src/main/java/com/forpets/be/global/mail/service/MailService.java
  be/src/main/java/com/forpets/be/global/mail/service/VerificationCodeService.java
  be/src/main/resources/application.properties
Labels: feat

#32 FR-41 [FE] 마이페이지 나의 아이 카드 컴포넌트 디자인 구현
  fe/src/components/mypage/AnimalCard.jsx
  fe/src/components/mypage/ProfileCard.jsx
  fe/src/pages/MyPage.jsx
Labels: feat, fix

#31 FR-38 [FE]: 채팅 페이지 레이아웃, 스타일 구현
  fe/src/pages/Chat.jsx
Labels: feat

#33 FR-43 [FE] 마이페이지 디자인 수정
  fe/src/components/mypage/AnimalCard.jsx
  fe/src/pages/MyPage.jsx
Labels: fix

#34 FR-44 [FE] 마이페이지 나의 봉사글 카드 컴포넌트 디자인 구현
  fe/src/components/mypage/VolunteerCard.jsx
Labels: feat

#35 FR-27 [BE] 액세스 토큰 및 리프레쉬 토큰 재발급
  be/src/main/java/com/forpets/be/global/auth/controller/AuthController.java
  be/src/main/java/com/forpets/be/global/auth/service/AuthService.java
  be/src/main/java/com/forpets/be/global/security/jwt/JwtTokenProvider.java
  be/src/main/java/com/forpets/be/global/util/CookieMaker.java
Labels: feat, fix

#37 FR-42 [FE] 회원가입 시 Gmail smtp를 사용한 이메일 인증 페이지 구현
  fe/src/api/authApi.js
  fe/src/pages/Signup.jsx
Labels: feat

#36 FR-45 [FE] 채팅 페이지 스타일 구현
  fe/src/components/ChatUserCard.jsx
  fe/src/pages/Chat.jsx
Labels: feat

#38 FR-48 [BE] 로그아웃 예외처리
  be/src/main/java/com/forpets/be/global/config/SecurityConfig.java
Labels: feat

#39 FR-47 [FE] 로그인 페이지 리프레쉬 토큰 api연결
  fe/src/api/authApi.js
  fe/src/api/axios.js
  fe/src/store/slices/authSlice.js
Labels: feat

#40 FR-53 [BE] Exception Handling
  be/src/main/java/com/forpets/be/global/exeption/GlobalExceptionHandler.java
  be/src/main/java/com/forpets/be/global/exeption/ResourceNotFoundException.java
  be/src/main/resources/application.properties
Labels: feat

#41 FR-56 [BE] Redis 로직 분리
  be/src/main/java/com/forpets/be/global/auth/service/AuthService.java
  be/src/main/java/com/forpets/be/global/redis/RedisRepository.java
Labels: refactor, feat

#42 FR-57 [FE] 구조동물 페이지 레이아웃, 스타일, api연결, footer컴포넌트픽스
  fe/src/Layout/MainLayout.jsx
  fe/src/components/Footer.jsx
  fe/src/components/Header.jsx
  fe/src/components/RescueAnimalCard.jsx
  fe/src/components/RescueAnimalDetail.jsx
  fe/src/pages/Chat.jsx
  fe/src/pages/Home.jsx
  fe/src/pages/RescueAnimals.jsx
  fe/src/router/index.jsx
Labels: feat

#43 FR-55 [BE] 나의 아이 entity 및 dto 만들기
  be/src/main/java/com/forpets/be/domain/animal/dto/request/MyAnimalCreateRequestDto.java
  be/src/main/java/com/forpets/be/domain/animal/dto/request/tmp
  be/src/main/java/com/forpets/be/domain/animal/dto/response/MyAnimalCreateResponseDto.java
  be/src/main/java/com/forpets/be/domain/animal/dto/response/tmp
  be/src/main/java/com/forpets/be/domain/animal/entity/MyAnimal.java
  be/src/main/java/com/forpets/be/domain/animal/entity/tmp
  be/src/main/java/com/forpets/be/domain/user/entity/User.java
  be/src/main/java/com/forpets/be/global/exeption/tmp
Labels: feat

#44 FR-46 [BE] 웹소켓 handshake 연결 구현
  be/build.gradle
  be/src/main/java/com/forpets/be/global/config/SecurityConfig.java
  be/src/main/java/com/forpets/be/global/websocket/config/WebSocketConfig.java
  be/src/main/java/com/forpets/be/global/websocket/handler/WebSocketHandler.java
Labels: chore, feat

#30 FR-37 [BE/FE] 봉사자 등록 프론트엔드와 백엔드 연동
  be/src/main/java/com/forpets/be/domain/servicevolunteer/controller/VolunteerController.java
  be/src/main/java/com/forpets/be/domain/servicevolunteer/dto/request/ServiceVolunteerRequestDto.java
  be/src/main/java/com/forpets/be/domain/servicevolunteer/dto/response/ServiceVolunteerResponseDto.java
  be/src/main/java/com/forpets/be/domain/servicevolunteer/entity/ServiceVolunteer.java
  be/src/main/java/com/forpets/be/domain/servicevolunteer/service/VolunteerService.java
  fe/package-lock.json
  fe/package.json
  fe/src/api/axios.js
  fe/src/api/volunteerApi.js
  fe/src/components/DaumPost.jsx
  fe/src/components/VolunteerCard.jsx
  fe/src/pages/RegisterVolunteer.jsx
  fe/src/pages/VolunteerList.jsx
  fe/src/router/index.jsx
  fe/src/store/slices/volunteerSlice.js
  fe/src/store/store.js
Labels: feat

#45 FR-59 [BE] 채팅방 생성 API 구현
  be/src/main/java/com/forpets/be/domain/chat/chatroom/controller/ChatRoomController.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/request/ChatRoomRequestDto.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/response/ChatRoomResponseDto.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/entity/ChatRoom.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/entity/RoomState.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/repository/ChatRoomRepository.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/service/ChatRoomService.java
Labels: feat

#46 FR-58 [FE] 구조동물 디테일 페이지 제작
  fe/src/components/Header.jsx
  fe/src/components/RescueAnimalCard.jsx
  fe/src/pages/RescueAnimalDetail.jsx
  fe/src/pages/RescueAnimalList.jsx
  fe/src/router/index.jsx
Labels: feat

#48 FR-64 [BE] 나의 아이 등록 create, read 구현
  be/src/main/java/com/forpets/be/domain/animal/controller/MyAnimalController.java
  be/src/main/java/com/forpets/be/domain/animal/controller/tmp
  be/src/main/java/com/forpets/be/domain/animal/dto/request/MyAnimalCreateRequestDto.java
  be/src/main/java/com/forpets/be/domain/animal/dto/response/AnimalsResponseDto.java
  be/src/main/java/com/forpets/be/domain/animal/dto/response/MyAnimalCreateResponseDto.java
  be/src/main/java/com/forpets/be/domain/animal/dto/response/MyAnimalReadResponseDto.java
  be/src/main/java/com/forpets/be/domain/animal/dto/tmp
  be/src/main/java/com/forpets/be/domain/animal/entity/MyAnimal.java
  be/src/main/java/com/forpets/be/domain/animal/repository/MyAnimalRepository.java
  be/src/main/java/com/forpets/be/domain/animal/repository/tmp
  be/src/main/java/com/forpets/be/domain/animal/service/MyAnimalService.java
  be/src/main/java/com/forpets/be/domain/animal/service/tmp
  be/src/main/java/com/forpets/be/domain/user/entity/User.java
Labels: feat, fix

#49 FR-50 [BE] 카카오 소셜 로그인 구현
  be/build.gradle
  be/src/main/java/com/forpets/be/domain/user/entity/User.java
  be/src/main/java/com/forpets/be/global/auth/controller/AuthController.java
  be/src/main/java/com/forpets/be/global/auth/dto/response/OAuth2ResponseDto.java
  be/src/main/java/com/forpets/be/global/auth/service/CustomOAuth2UserService.java
  be/src/main/java/com/forpets/be/global/auth/service/NicknameGenerator.java
  be/src/main/java/com/forpets/be/global/auth/service/OAuth2AuthenticationSuccessHandler.java
  be/src/main/java/com/forpets/be/global/auth/service/OAuth2UserInfo.java
  be/src/main/java/com/forpets/be/global/config/SecurityConfig.java
  be/src/main/resources/application.properties
  be/src/main/resources/application.yml
  be/src/main/resources/static/favicon.ico
Labels: feat

#51 FR-66 [FE] 메인페이지 나의아이 api 연결
  fe/src/api/animalsApi.js
  fe/src/components/KakaoMap.jsx
  fe/src/components/MainAnimalCard.jsx
  fe/src/pages/Home.jsx
Labels: feat

#52 FR-70 [BE] 소셜 로그인 코드 수정 및 yml 복구
  be/src/main/java/com/forpets/be/domain/user/entity/User.java
  be/src/main/java/com/forpets/be/global/auth/service/CustomOAuth2UserService.java
  be/src/main/java/com/forpets/be/global/auth/service/OAuth2AuthenticationSuccessHandler.java
  be/src/main/java/com/forpets/be/global/auth/service/OAuth2UserInfo.java
  be/src/main/resources/application.yml
Labels: feat

#50 FR-51 [FE] 카카오 소셜 로그인 프론트 구현
  fe/src/pages/Login.jsx
  fe/src/pages/SocialLogin.jsx
  fe/src/router/index.jsx
Labels: feat

#53 FR-67 [BE] 나의 아이 개별 상세 조회
  be/src/main/java/com/forpets/be/domain/animal/controller/MyAnimalController.java
  be/src/main/java/com/forpets/be/domain/animal/entity/MyAnimal.java
  be/src/main/java/com/forpets/be/domain/animal/repository/MyAnimalRepository.java
  be/src/main/java/com/forpets/be/domain/animal/service/MyAnimalService.java
Labels: feat, fix

#55 FR-65 [BE] 채팅방 생성 API 추가 구현
  be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/request/ChatRoomRequestDto.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/response/ChatRoomResponseDto.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/entity/ChatRoom.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/service/ChatRoomService.java
Labels: feat, fix

#56 FR-72 [BE] 내가 요청자로 속한 채팅방 전체 조회 API 수정
  be/src/main/java/com/forpets/be/domain/chat/chatroom/controller/ChatRoomController.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/response/ChatRoomsListResponseDto.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/service/ChatRoomService.java
  be/src/main/java/com/forpets/be/domain/chatroom/controller/tmp
  be/src/main/java/com/forpets/be/domain/chatroom/dto/request/tmp
  be/src/main/java/com/forpets/be/domain/chatroom/dto/response/tmp
  be/src/main/java/com/forpets/be/domain/chatroom/dto/tmp
  be/src/main/java/com/forpets/be/domain/chatroom/entity/tmp
  be/src/main/java/com/forpets/be/domain/chatroom/repository/tmp
  be/src/main/java/com/forpets/be/domain/chatroom/service/tmp
Labels: fix

#57 FR-71 [FE] 메인페이지 출발지 도착지 마커구현
  fe/src/components/KakaoMap.jsx
Labels: feat

#59 FR-74 [BE] 내가 봉사자로 속한 채팅방 전체 조회 API 구현
  be/src/main/java/com/forpets/be/domain/chat/chatroom/controller/ChatRoomController.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/response/ChatRoomsListResponseDto.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/response/RequestorChatRoomsListResponseDto.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/response/RequestorChatRoomsResponseDto.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/response/VolunteerChatRoomsListResponseDto.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/response/VolunteerChatRoomsResponseDto.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/repository/ChatRoomRepository.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/service/ChatRoomService.java
  be/src/main/java/com/forpets/be/global/auth/service/OAuth2AuthenticationSuccessHandler.java
Labels: feat, fix

#61 FR-61 [FE] 봉사자 조회 구현
  be/src/main/java/com/forpets/be/domain/servicevolunteer/controller/VolunteerController.java
  be/src/main/java/com/forpets/be/domain/servicevolunteer/dto/request/ServiceVolunteerListRequestDto.java
  be/src/main/java/com/forpets/be/domain/servicevolunteer/dto/response/ServiceVolunteerListResponseDto.java
  be/src/main/java/com/forpets/be/domain/servicevolunteer/service/VolunteerService.java
  fe/public/assets/person.jpeg
  fe/src/components/VolunteerCard.jsx
  fe/src/pages/VolunteerList.jsx
Labels: feat

#54 FR-63 [BE] 봉사자 등록 페이지 구현
  be/src/main/java/com/forpets/be/domain/servicevolunteer/controller/VolunteerController.java
  be/src/main/java/com/forpets/be/domain/servicevolunteer/dto/request/ServiceVolunteerListRequestDto.java
  be/src/main/java/com/forpets/be/domain/servicevolunteer/dto/response/ServiceVolunteerListResponseDto.java
  be/src/main/java/com/forpets/be/domain/servicevolunteer/repository/VolunteerRepository.java
  be/src/main/java/com/forpets/be/domain/servicevolunteer/service/VolunteerService.java
  fe/src/pages/VolunteerList.jsx
  fe/src/router/index.jsx
Labels: feat

#60 FR-77 [FE] 메인페이지 마커 기능 추가
  be/src/main/java/com/forpets/be/global/config/SecurityConfig.java
  fe/public/assets/forpets-marker-2.png
  fe/public/assets/forpets-marker.png
  fe/src/api/animalsApi.js
  fe/src/components/KakaoMap.jsx
  fe/src/pages/Home.jsx
Labels: feat

#63 FR-80 배포 테스트
  fe/src/pages/ServiceStatus.jsx
Labels: chore

#64 FR-81 배포 테스트
  .github/workflows/workflows.yml
Labels: chore

#66 FR-76 [BE] 채팅 메시지 발신, 수신 API 구현
  be/src/main/java/com/forpets/be/domain/chat/chatmessage/controller/ChatMessageController.java
  be/src/main/java/com/forpets/be/domain/chat/chatmessage/dto/request/ChatMessageRequestDto.java
  be/src/main/java/com/forpets/be/domain/chat/chatmessage/entity/ChatMessage.java
  be/src/main/java/com/forpets/be/domain/chat/chatmessage/repository/ChatMessageRepository.java
  be/src/main/java/com/forpets/be/domain/chat/chatmessage/service/ChatMessageService.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/repository/ChatRoomRepository.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/service/ChatRoomService.java
  be/src/main/java/com/forpets/be/global/websocket/config/WebSocketConfig.java
  be/src/main/java/com/forpets/be/global/websocket/handler/StompHandler.java
  be/src/main/java/com/forpets/be/global/websocket/handler/WebSocketHandler.java
Labels: feat

#67 [FR-84] github-workflows.yml docker 비밀번호를 토큰으로 변경
  .github/workflows/workflows.yml
Labels: chore

#68 FR-79 [FE] 메인페이지 봉사자 마커 구현
  fe/src/components/KakaoMap.jsx
  fe/src/components/MainAnimalCard.jsx
  fe/src/components/MainVolunteerCard.jsx
  fe/src/pages/Home.jsx
Labels: feat

#69 FR-83 [BE] 채팅방 상세 조회 API 구현
  be/src/main/java/com/forpets/be/domain/chat/chatmessage/dto/response/ChatMessageResponseDto.java
  be/src/main/java/com/forpets/be/domain/chat/chatmessage/repository/ChatMessageRepository.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/controller/ChatRoomController.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/response/ChatRoomDetailResponseDto.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/repository/ChatRoomRepository.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/service/ChatRoomService.java
Labels: feat

#71 FR-75 [FE] 나의 아이 등록 화면 구현
  be/src/main/java/com/forpets/be/global/config/SecurityConfig.java
  fe/package-lock.json
  fe/package.json
  fe/src/assets/forpetsLogo.png
  fe/src/pages/RegisterAnimal.jsx
  fe/src/styles/index.css
Labels: chore, feat

#72 FR-90[FE] 봉사자 등록 수정사항 반영
  fe/src/components/VolunteerCard.jsx
  package-lock.json
  package.json
Labels: chore, fix

#74 FR-92 [BE] 로그인 및 재발급 시 userId 전달 추가
  be/src/main/java/com/forpets/be/global/auth/controller/AuthController.java
  be/src/main/java/com/forpets/be/global/auth/dto/response/TokenResponseDto.java
  be/src/main/java/com/forpets/be/global/auth/service/AuthService.java
  be/src/main/java/com/forpets/be/global/security/jwt/TokenAndIdDto.java
Labels: feat, fix

#76 FR-89 [BE] 채팅, 나의 아이 응답 데이터 코드 수정
  be/src/main/java/com/forpets/be/domain/animal/dto/response/MyAnimalReadResponseDto.java
  be/src/main/java/com/forpets/be/domain/chat/chatmessage/dto/response/ChatMessageResponseDto.java
  be/src/main/java/com/forpets/be/domain/chat/chatmessage/entity/ChatMessage.java
  be/src/main/java/com/forpets/be/domain/chat/chatmessage/service/ChatMessageService.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/controller/ChatRoomController.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/response/ChatRoomDetailResponseDto.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/response/ChatRoomResponseDto.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/response/RequestorChatRoomsResponseDto.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/response/VolunteerChatRoomsResponseDto.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/entity/ChatRoom.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/repository/ChatRoomRepository.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/service/ChatRoomService.java
  be/src/main/java/com/forpets/be/global/config/SecurityConfig.java
Labels: feat, fix

#75 FR-93 [FE]네이버 소셜 로그인 구현
  fe/src/components/VolunteerCard.jsx
  fe/src/pages/Login.jsx
Labels: feat

#77 FR-96 배포 테스트
  .github/workflows/workflows.yml
Labels: chore

#78 FR-94 [FE] 나의 아이 등록 기능 구현 및 수정
  fe/src/pages/RegisterAnimal.jsx
Labels: feat, fix

#79 FR-95 [BE] 채팅방 수정 API 구현
  .github/workflows/workflows.yml
  be/src/main/java/com/forpets/be/domain/chat/chatroom/controller/ChatRoomController.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/request/ChatRoomUpdateRequestRecord.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/entity/ChatRoom.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/service/ChatRoomService.java
Labels: feat, fix

#81 FR-97 [FE] 나의 아이 더보기 리스트 화면 구현
  .github/workflows/workflows.yml
  be/src/main/java/com/forpets/be/domain/animal/dto/request/MyAnimalCreateRequestDto.java
  be/src/main/java/com/forpets/be/domain/animal/repository/MyAnimalRepository.java
  be/src/main/java/com/forpets/be/domain/animal/service/MyAnimalService.java
  fe/src/components/AnimalCard.jsx
  fe/src/pages/AnimalList.jsx
Labels: feat, fix

#82 FR-101 [FE] 토큰 만료 시 발생하는 401 에러 지연 시간 설정
  fe/src/api/axios.js
Labels: feat

#84 FR-98 [BE] 채팅방 퇴장/삭제 API 구현
  be/src/main/java/com/forpets/be/domain/chat/chatmessage/entity/ChatMessage.java
  be/src/main/java/com/forpets/be/domain/chat/chatmessage/service/ChatMessageService.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/controller/ChatRoomController.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/entity/ChatRoom.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/repository/ChatRoomRepository.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/service/ChatRoomService.java
  be/src/main/java/com/forpets/be/global/websocket/config/WebSocketConfig.java
Labels: feat, fix

#86 FR-52 [FE] 회원가입 페이지 리펙토링
  fe/package-lock.json
  fe/package.json
  fe/src/pages/Signup.jsx
  fe/vite.config.js
Labels: refactor

#87 FR-102 [BE] 이동봉사 현황 생성 API 구현
  be/src/main/java/com/forpets/be/domain/chat/chatroom/controller/ChatRoomController.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/request/ChatRoomUpdateRequestRecord.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/response/ChatRoomDetailResponseDto.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/response/ChatRoomResponseDto.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/response/RequestorChatRoomsResponseDto.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/response/VolunteerChatRoomsResponseDto.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/entity/ChatRoom.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/entity/RoomState.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/service/ChatRoomService.java
  be/src/main/java/com/forpets/be/domain/servicestatus/controller/tmp
  be/src/main/java/com/forpets/be/domain/servicestatus/dto/request/tmp
  be/src/main/java/com/forpets/be/domain/servicestatus/dto/response/tmp
  be/src/main/java/com/forpets/be/domain/servicestatus/dto/tmp
  be/src/main/java/com/forpets/be/domain/servicestatus/entity/tmp
  be/src/main/java/com/forpets/be/domain/servicestatus/repository/tmp
  be/src/main/java/com/forpets/be/domain/servicestatus/service/tmp
  be/src/main/java/com/forpets/be/domain/volunteerworkstatus/controller/VolunteerWorkStatusController.java
  be/src/main/java/com/forpets/be/domain/volunteerworkstatus/dto/request/VolunteerWorkStatusRequestDto.java
  be/src/main/java/com/forpets/be/domain/volunteerworkstatus/dto/response/VolunteerWorkStatusResponseDto.java
  be/src/main/java/com/forpets/be/domain/volunteerworkstatus/entity/VolunteerWorkStatus.java
  be/src/main/java/com/forpets/be/domain/volunteerworkstatus/entity/WorkState.java
  be/src/main/java/com/forpets/be/domain/volunteerworkstatus/repository/VolunteerWorkStatusRepository.java
  be/src/main/java/com/forpets/be/domain/volunteerworkstatus/service/VolunteerWorkStatusService.java
Labels: feat, fix

#88 FR-107 배포 테스트
  be/src/main/java/com/forpets/be/global/exeption/GlobalExceptionHandler.java
  be/src/main/java/com/forpets/be/global/security/handler/JwtAuthenticationEntryPoint.java
  fe/package-lock.json
Labels: chore

#90 FR-109 배포 테스트 4
  be/src/main/resources/application.yml
Labels: chore

#92 FR-100 [FE] 나의 아이 상세페이지 구현
  fe/src/api/animalsApi.js
  fe/src/components/AnimalCard.jsx
  fe/src/pages/AnimalDetail.jsx
  fe/src/pages/RegisterAnimal.jsx
Labels: refactor, feat

#93 FR-110 [BE] 나의 아이 dto 및 응답코드 수정
  be/src/main/java/com/forpets/be/domain/animal/controller/MyAnimalController.java
  be/src/main/java/com/forpets/be/domain/animal/dto/request/MyAnimalCreateRequestDto.java
  be/src/main/java/com/forpets/be/domain/animal/dto/request/MyAnimalUpdateRequestDto.java
Labels: fix

#94 FR-113 배포 테스트 5
  be/src/main/resources/application.yml
Labels: chore

#95 FR-103 [BE] 봉사자 등록글 개별 삭제
  be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/request/ChatRoomRequestDto.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/response/ChatRoomResponseDto.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/entity/ChatRoom.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/repository/ChatRoomRepository.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/service/ChatRoomService.java
  be/src/main/java/com/forpets/be/domain/servicevolunteer/controller/VolunteerController.java
  be/src/main/java/com/forpets/be/domain/servicevolunteer/dto/request/ServiceVolunteerListRequestDto.java
  be/src/main/java/com/forpets/be/domain/servicevolunteer/dto/request/ServiceVolunteerRequestDto.java
  be/src/main/java/com/forpets/be/domain/servicevolunteer/dto/response/ServiceVolunteerDetailResponseDto.java
  be/src/main/java/com/forpets/be/domain/servicevolunteer/dto/response/ServiceVolunteerListResponseDto.java
  be/src/main/java/com/forpets/be/domain/servicevolunteer/dto/response/ServiceVolunteerResponseDto.java
  be/src/main/java/com/forpets/be/domain/servicevolunteer/entity/VolunteerWork.java
  be/src/main/java/com/forpets/be/domain/servicevolunteer/repository/VolunteerRepository.java
  be/src/main/java/com/forpets/be/domain/servicevolunteer/service/VolunteerService.java
Labels: feat, fix

#96 FR-111 [BE] 나의 이동봉사 현황 조회 API 구현
  be/src/main/java/com/forpets/be/domain/volunteerworkstatus/controller/VolunteerWorkStatusController.java
  be/src/main/java/com/forpets/be/domain/volunteerworkstatus/repository/VolunteerWorkStatusRepository.java
  be/src/main/java/com/forpets/be/domain/volunteerworkstatus/service/VolunteerWorkStatusService.java
Labels: feat, fix

#97 FR-114 [BE] 채팅 코드 수정
  be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/response/RequestorChatRoomsResponseDto.java
Labels: fix

#98 FR-115 배포 테스트 6
  be/src/main/resources/application.yml
Labels: chore

#100 [FR-117] 깃허브액션 수정
  .github/workflows/workflows.yml
Labels: chore

#99 FR-105 [FE] 봉사자 디테일페이지 채팅 연결
  fe/index.html
  fe/src/api/animalsApi.js
  fe/src/api/chatApi.js
  fe/src/components/MainAnimalCard.jsx
  fe/src/components/MainVolunteerCard.jsx
  fe/src/components/chat/ChatMessages.jsx
  fe/src/components/volunteer/VolunteerCard.jsx
  fe/src/components/volunteer/VolunteerChatModal.jsx
  fe/src/components/volunteer/VolunteerEditModal.jsx
  fe/src/pages/Chat.jsx
  fe/src/pages/VolunteerDetail.jsx
  fe/src/pages/VolunteerList.jsx
Labels: feat

#103 FR-118 [FE] 나의아이 페이지 채팅 연결
  fe/src/pages/AnimalDetail.jsx
Labels: feat

#105 FR-120 [BE] 이동봉사 현황 삭제 API 구현
  be/src/main/java/com/forpets/be/domain/volunteerworkstatus/controller/VolunteerWorkStatusController.java
  be/src/main/java/com/forpets/be/domain/volunteerworkstatus/service/VolunteerWorkStatusService.java
Labels: feat
