Repository Team-ForPets/forpets-web, pull requests merged in 2025-04, with the labels that each got.

#107 FR-121 [BE] 이동봉사 현황 수정 API 구현
  be/src/main/java/com/forpets/be/domain/volunteerworkstatus/controller/VolunteerWorkStatusController.java
  be/src/main/java/com/forpets/be/domain/volunteerworkstatus/dto/response/VolunteerWorkStatusResponseDto.java
  be/src/main/java/com/forpets/be/domain/volunteerworkstatus/entity/VolunteerWorkStatus.java
  be/src/main/java/com/forpets/be/domain/volunteerworkstatus/repository/VolunteerWorkStatusRepository.java
  be/src/main/java/com/forpets/be/domain/volunteerworkstatus/service/VolunteerWorkStatusService.java
Labels: feat, fix

#108 FR-123 배포 테스트 7
  be/src/main/java/com/forpets/be/global/config/RedisConfig.java
  be/src/main/resources/application.yml
  docker-compose.yml
  fe/Dockerfile
Labels: chore

#106 FR-122 [FE] 이동 봉사 현황 페이지 구현
  fe/src/api/serviceStatusApi.js
  fe/src/api/volunteerWorkStatusApi.js
  fe/src/components/Header.jsx
  fe/src/components/VolunteerWorkStatusCard.jsx
  fe/src/pages/ServiceStatus.jsx
  fe/src/pages/VolunteerWorkStatus.jsx
  fe/src/router/index.jsx
Labels: feat

#110 FR-125 배포 테스트 8
  be/src/main/java/com/forpets/be/RedisConnectionTestController.java
  be/src/main/java/com/forpets/be/global/config/RedisConfig.java
  be/src/main/resources/application.yml
Labels: chore, fix

#112 FR-128 [BE] aws s3 구성 파일
  be/src/main/java/com/forpets/be/global/aws/AwsS3Config.java
  be/src/main/java/com/forpets/be/global/aws/S3Service.java
Labels: feat

#114 FR-129 로컬 / 배포 서버 구분용 환경변수 설정
  be/src/main/java/com/forpets/be/global/auth/service/OAuth2AuthenticationSuccessHandler.java
  be/src/main/java/com/forpets/be/global/config/SecurityConfig.java
  be/src/main/java/com/forpets/be/global/websocket/config/WebSocketConfig.java
  be/src/main/resources/application.yml
  fe/Dockerfile
  fe/src/components/chat/ChatMessages.jsx
  fe/src/pages/Login.jsx
Labels: chore

#115 FR-131 환경 변수 수정
  be/src/main/resources/application.yml
  fe/src/components/chat/ChatMessages.jsx
  fe/src/pages/Login.jsx
Labels: fix

#116 FR-130 [FE] 이동 봉사 현황 페이지 수정
  fe/src/pages/VolunteerWorkStatus.jsx
Labels: fix

#118 FR-119 [FE] 채팅 페이지 웹소켓구현
  fe/src/api/stompClient.js
  fe/src/components/ChatModal.jsx
  fe/src/components/ChatRoomCard.jsx
  fe/src/components/chat/ChatAnimalInfoModal.jsx
  fe/src/components/chat/ChatMessages.jsx
  fe/src/components/chat/ChatRoomHeader.jsx
  fe/src/components/chat/ChatUserCard.jsx
  fe/src/pages/Chat.jsx
Labels: feat

#120 FR-119 [FE] 채팅 페이지 웹소켓 구현
  fe/src/components/chat/ChatMessages.jsx
  fe/src/pages/Chat.jsx
Labels: feat

#121 FR-134 [FE] 채팅 페이지 코드 리펙토링
  fe/src/components/chat/ChatMessages.jsx
Labels: fix

#122 FR-136 Dockerfile에 환경변수 삽입
  docker-compose.yml
  fe/Dockerfile
Labels: chore

#124 FR-135 [FE] 이동봉사 현황 생성
  fe/src/api/volunteerWorkStatusApi.js
  fe/src/components/PromiseModal.jsx
  fe/src/components/VolunteerWorkStatusCard.jsx
  fe/src/components/chat/ChatRoomHeader.jsx
  fe/src/pages/Chat.jsx
  fe/src/pages/VolunteerWorkStatus.jsx
Labels: feat

#125 FR-133 [BE] 마이페이지 회원정보 수정 비밀번호 검증 API 구현
  be/src/main/java/com/forpets/be/domain/user/controller/UserController.java
  be/src/main/java/com/forpets/be/domain/user/dto/request/UserPasswordRequestRecord.java
  be/src/main/java/com/forpets/be/domain/user/repository/UserRepository.java
  be/src/main/java/com/forpets/be/domain/user/service/UserService.java
Labels: feat

#126 FR-138 [FE] 마이페이지 나의 아이, 나의 봉사글 카드 컴포넌트 수정
  fe/src/components/mypage/AnimalCard.jsx
  fe/src/components/mypage/ProfileCard.jsx
  fe/src/components/mypage/VolunteerCard.jsx
Labels: fix

#127 FR-140 [FE] 이동 봉사 현황 페이지 수정
  be/src/main/java/com/forpets/be/global/config/SecurityConfig.java
  fe/src/pages/VolunteerWorkStatus.jsx
Labels: feat

#131 FR-144 [FE/BE] 소셜 로그인 도메인 수정
  be/src/main/java/com/forpets/be/global/auth/service/CustomOAuth2UserService.java
  be/src/main/resources/application.yml
  docker-compose.yml
  fe/Dockerfile
  fe/src/pages/Login.jsx
Labels: fix

#129 FR-143 [BE] 봉사자 등록글 수정
  be/src/main/java/com/forpets/be/domain/animal/dto/request/MyAnimalCreateRequestDto.java
  be/src/main/java/com/forpets/be/domain/animal/dto/request/MyAnimalUpdateRequestDto.java
  be/src/main/java/com/forpets/be/domain/animal/dto/response/MyAnimalResponseDto.java
  be/src/main/java/com/forpets/be/domain/animal/entity/MyAnimal.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/entity/ChatRoom.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/service/ChatRoomService.java
  be/src/main/java/com/forpets/be/domain/servicevolunteer/dto/request/ServiceVolunteerListRequestDto.java
  be/src/main/java/com/forpets/be/domain/servicevolunteer/repository/VolunteerRepository.java
  be/src/main/java/com/forpets/be/domain/servicevolunteer/service/VolunteerService.java
  be/src/main/java/com/forpets/be/domain/volunteerwork/controller/VolunteerController.java
  be/src/main/java/com/forpets/be/domain/volunteerwork/dto/request/VolunteerWokrUpdateRequestDto.java
  be/src/main/java/com/forpets/be/domain/volunteerwork/dto/request/VolunteerWorkRequestDto.java
  be/src/main/java/com/forpets/be/domain/volunteerwork/dto/response/VolunteerWorkDetailResponseDto.java
  be/src/main/java/com/forpets/be/domain/volunteerwork/dto/response/VolunteerWorkListResponseDto.java
  be/src/main/java/com/forpets/be/domain/volunteerwork/dto/response/VolunteerWorkResponseDto.java
  be/src/main/java/com/forpets/be/domain/volunteerwork/entity/AnimalType.java
  be/src/main/java/com/forpets/be/domain/volunteerwork/entity/VolunteerWork.java
  be/src/main/java/com/forpets/be/domain/volunteerwork/repository/VolunteerWorkRepository.java
  be/src/main/java/com/forpets/be/domain/volunteerwork/service/VolunteerWorkService.java
Labels: fix

#133 FR-144 [FE/BE] 소셜 로그인 도메인 수정
  docker-compose.yml
Labels: fix

#134 FR-141 [BE] 마이페이지 회원정보(프로필) 수정 API 구현
  be/src/main/java/com/forpets/be/domain/user/controller/UserController.java
  be/src/main/java/com/forpets/be/domain/user/dto/request/tmp
  be/src/main/java/com/forpets/be/domain/user/entity/User.java
  be/src/main/java/com/forpets/be/domain/user/my/controller/MyController.java
  be/src/main/java/com/forpets/be/domain/user/my/dto/request/MyProfileUpdateRequestDto.java
  be/src/main/java/com/forpets/be/domain/user/my/dto/request/UserPasswordRequestRecord.java
  be/src/main/java/com/forpets/be/domain/user/my/dto/response/MyProfileUpdateResponseDto.java
  be/src/main/java/com/forpets/be/domain/user/my/service/MyService.java
  be/src/main/java/com/forpets/be/domain/user/service/UserService.java
  be/src/main/java/com/forpets/be/global/config/SecurityConfig.java
  be/src/main/resources/application.yml
Labels: feat, fix

#135 Update README.md
  README.md
Labels: documentation

#136 Update README.md
  README.md
Labels: documentation

#140 Update README.md
  README.md
Labels: documentation

#139 FR-147 [FE/BE] 소셜 로그인 env 수정
  docker-compose.yml
  fe/Dockerfile
  fe/templates/default.conf.template
  fe/templates/https.conf.template
Labels: fix

#141 Update README.md
  README.md
Labels: documentation

#142 FR-148 [BE] 마이페이지 나의 봉사글 조회 API 구현
  be/src/main/java/com/forpets/be/domain/volunteerwork/controller/VolunteerController.java
  be/src/main/java/com/forpets/be/domain/volunteerwork/dto/response/MyVolunteerWorkListResponseDto.java
  be/src/main/java/com/forpets/be/domain/volunteerwork/dto/response/MyVolunteerWorkResponseDto.java
  be/src/main/java/com/forpets/be/domain/volunteerwork/repository/VolunteerWorkRepository.java
  be/src/main/java/com/forpets/be/domain/volunteerwork/service/VolunteerWorkService.java
  fe/src/api/volunteerApi.js
Labels: feat

#144 FR-151 [BE] 나의 아이 기존 사진 삭제 기능 구현
  be/src/main/java/com/forpets/be/domain/animal/dto/request/MyAnimalUpdateRequestDto.java
  be/src/main/java/com/forpets/be/domain/animal/dto/response/MyAnimalResponseDto.java
  be/src/main/java/com/forpets/be/domain/animal/service/MyAnimalService.java
Labels: feat, fix

#143 FR-146 [FE] 전체 페이지 오류 수정
  .gitattributes
  README.md
  fe/public/assets/forpets-logo.png
  fe/public/assets/gif/login.gif
  fe/public/assets/gif/나의아이등록.gif
  fe/src/components/Header.jsx
  fe/src/components/MainAnimalCard.jsx
  fe/src/components/MainVolunteerCard.jsx
  fe/src/components/PromiseModal.jsx
  fe/src/components/PromiseStatusModal.jsx
  fe/src/components/chat/ChatRoomHeader.jsx
  fe/src/pages/Chat.jsx
  fe/src/pages/Home.jsx
  fe/src/pages/Login.jsx
  fe/src/pages/RegisterAnimal.jsx
Labels: feat, fix

#146 FR-153 [FE] 나의 아이 등록 Content-Type 에러 수정
  fe/src/api/animalsApi.js
  fe/src/pages/RegisterAnimal.jsx
Labels: fix

#145 FR-152 [FE] README gif 추가
  .gitattributes
  fe/public/assets/gif/registerAnimal.gif
Labels: feat

#149 FR-150 [FE] 마이페이지 나의 봉사글 조회 API 연동
  be/src/main/java/com/forpets/be/domain/volunteerwork/dto/response/MyVolunteerWorkResponseDto.java
  fe/src/api/mypageApi.js
  fe/src/components/mypage/VolunteerCard.jsx
  fe/src/components/mypage/VolunteerCardList.jsx
  fe/src/pages/MyPage.jsx
  fe/src/router/index.jsx
Labels: feat, fix

#151 FR-145 [FE/BE] 마이페이지 회원정보(프로필) 수정 기능 구현
  be/src/main/java/com/forpets/be/domain/user/my/controller/MyController.java
  be/src/main/java/com/forpets/be/domain/user/my/service/MyService.java
  fe/src/api/mypageApi.js
  fe/src/components/mypage/ProfileCard.jsx
  fe/src/components/mypage/ProfileEditCard.jsx
  fe/src/pages/MyPage.jsx
Labels: feat

#152 FR-145 [FE] 마이페이지 회원정보(프로필) 수정 기능 구현
  fe/src/api/mypageApi.js
Labels: feat

#155 FR-156 [FE] 마이페이지 나의 아이 조회 API 연동
  fe/src/components/mypage/AnimalCard.jsx
  fe/src/components/mypage/AnimalCardList.jsx
  fe/src/router/index.jsx
Labels: feat

#156 FR-158 Nginx 수정
  docker-compose.yml
  fe/Dockerfile
  fe/templates/default.conf.template
Labels: chore

#159 FR-163 [FE] 로그인 페이지 수정
  fe/src/pages/Login.jsx
Labels: fix

#160 FR-160 [BE] 채팅방 상세 조회 코드 수정
  be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/response/ChatRoomDetailResponseDto.java
  be/src/main/java/com/forpets/be/domain/chat/chatroom/service/ChatRoomService.java
Labels: fix

#161 FR-165 [FE] 이동봉사현황 수정 삭제 구현
  be/src/main/resources/application.yml
  fe/src/api/volunteerWorkStatusApi.js
  fe/src/components/Modal.jsx
  fe/src/components/PromiseModal.jsx
  fe/src/components/chat/ChatRoomHeader.jsx
  fe/src/components/chat/ChatUserCard.jsx
  fe/src/components/chat/PromiseModal.jsx
  fe/src/pages/Chat.jsx
Labels: feat

#162 FR-164 [FE] 마이페이지 스크롤 수정
  fe/src/components/mypage/AnimalCard.jsx
  fe/src/components/mypage/AnimalCardList.jsx
  fe/src/components/mypage/VolunteerCardList.jsx
  fe/src/pages/MyPage.jsx
Labels: fix

#163 FR-168 [BE] 이동봉사 현황 코드 수정
  be/src/main/java/com/forpets/be/domain/volunteerworkstatus/dto/request/VolunteerWorkStatusRequestDto.java
  be/src/main/java/com/forpets/be/domain/volunteerworkstatus/dto/response/VolunteerWorkStatusResponseDto.java
  be/src/main/java/com/forpets/be/domain/volunteerworkstatus/entity/VolunteerWorkStatus.java
  be/src/main/java/com/forpets/be/domain/volunteerworkstatus/service/VolunteerWorkStatusService.java
Labels: fix

#168 FR-172 [FE] 소셜 로그인 프록시 설정
  fe/templates/https.conf.template
Labels: fix

#169 FR-173 [FE] 소셜 로그인 프록시 재설정2
  fe/templates/https.conf.template
Labels: fix

#170 FR-174 [FE] 로그인 페이지 수정
  fe/src/pages/Login.jsx
Labels: fix

#171 FR-175 [BE] 네이버 소셜 로그인 redirect-uri 수정 테스트
  be/src/main/resources/application.yml
Labels: fix

#173 FR-176 [FE] 메인, 이동봉사 현황 코드 수정
  fe/index.html
  fe/src/components/VolunteerWorkStatusCard.jsx
Labels: fix

#175 FR-137 [FE] 회원가입 페이지 리펙토링
  fe/src/pages/Signup.jsx
Labels: feat, fix
